name: Auto Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install dotnet outdated tool
      run: dotnet tool install --global dotnet-outdated-tool
      
    - name: Check for outdated packages
      id: check-outdated
      run: |
        # Check for outdated packages and create update report
        dotnet outdated --output json > outdated-report.json
        
        # Check if there are any outdated packages
        if [ -s outdated-report.json ] && [ "$(cat outdated-report.json)" != "[]" ]; then
          echo "has-updates=true" >> $GITHUB_OUTPUT
          echo "📦 Found outdated packages"
        else
          echo "has-updates=false" >> $GITHUB_OUTPUT
          echo "✅ All packages are up to date"
        fi
        
    - name: Update packages
      if: steps.check-outdated.outputs.has-updates == 'true'
      run: |
        # Update packages (only minor and patch versions for safety)
        dotnet outdated --upgrade --version-lock Major
        
        # Restore and build to ensure updates work
        dotnet restore
        dotnet build --configuration Release
        
    - name: Run tests after update
      if: steps.check-outdated.outputs.has-updates == 'true'
      run: |
        dotnet test --configuration Release --verbosity normal
        
    - name: Create Pull Request
      if: steps.check-outdated.outputs.has-updates == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "chore: Auto-update dependencies"
        body: |
          ## 🤖 Automated Dependency Updates
          
          This PR contains automatic updates to project dependencies.
          
          ### Changes
          - Updated NuGet packages to latest compatible versions
          - Only minor and patch version updates are included for safety
          - All tests pass with the updated dependencies
          
          ### Verification
          - ✅ Solution builds successfully
          - ✅ All tests pass
          - ✅ No breaking changes detected
          
          Please review the changes and merge if everything looks good.
          
          Generated by: Auto Update Dependencies workflow
        branch: auto-update-dependencies
        delete-branch: true
        labels: |
          dependencies
          automated
          
  update-dotnet-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for .NET updates
      id: check-dotnet
      run: |
        # Get current .NET version from global.json
        CURRENT_VERSION=$(cat global.json | grep -o '"version": "[^"]*"' | cut -d'"' -f4)
        echo "Current .NET version: $CURRENT_VERSION"
        
        # Get latest .NET 9.0 version
        LATEST_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json | \
          grep -o '"9\.[0-9]\+\.[0-9]\+"' | \
          sort -V | \
          tail -1 | \
          tr -d '"')
        
        echo "Latest .NET 9.0 version: $LATEST_VERSION"
        
        if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
          echo "has-update=true" >> $GITHUB_OUTPUT
          echo "new-version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "📦 .NET version update available: $CURRENT_VERSION -> $LATEST_VERSION"
        else
          echo "has-update=false" >> $GITHUB_OUTPUT
          echo "✅ .NET version is up to date"
        fi
        
    - name: Update .NET version
      if: steps.check-dotnet.outputs.has-update == 'true'
      run: |
        NEW_VERSION="${{ steps.check-dotnet.outputs.new-version }}"
        
        # Update global.json
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" global.json
        
        # Update CLAUDE.md
        sed -i "s/Required SDK: [0-9]\+\.[0-9]\+\.[0-9]\+/Required SDK: $NEW_VERSION/" CLAUDE.md
        
        echo "Updated .NET version to $NEW_VERSION"
        
    - name: Test with new .NET version
      if: steps.check-dotnet.outputs.has-update == 'true'
      run: |
        # Setup the new .NET version
        curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version ${{ steps.check-dotnet.outputs.new-version }}
        
        # Test build with new version
        dotnet restore
        dotnet build --configuration Release
        dotnet test --configuration Release
        
    - name: Create .NET update PR
      if: steps.check-dotnet.outputs.has-update == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update .NET SDK to ${{ steps.check-dotnet.outputs.new-version }}"
        title: "chore: Update .NET SDK to ${{ steps.check-dotnet.outputs.new-version }}"
        body: |
          ## 🔄 .NET SDK Update
          
          Updates the .NET SDK version to the latest available.
          
          ### Changes
          - Updated `global.json` SDK version
          - Updated documentation references
          - Verified compatibility with new SDK version
          
          ### Version Details
          - **Previous**: Current version in global.json
          - **New**: ${{ steps.check-dotnet.outputs.new-version }}
          
          ### Verification
          - ✅ Solution builds successfully with new SDK
          - ✅ All tests pass
          - ✅ No compatibility issues detected
          
          Generated by: Auto Update Dependencies workflow
        branch: update-dotnet-sdk
        delete-branch: true
        labels: |
          dependencies
          dotnet
          automated